---
title: "Exercise 12.6.1"
author: "Xiru Lyu"
date: "2/20/2018"
output: 
  pdf_document: default
---

```{r, message=FALSE}
# load in required package
library(tidyverse)
```

## 3. I claimed that `iso2` and `iso3` were redundant with country. Confirm this claim.
```{r}
# import the dataset

who <- who %>% gather(code, value, new_sp_m014:newrel_f65, na.rm = TRUE) %>% 
  mutate(code = stringr::str_replace(code, "newrel", "new_rel")) %>%
  separate(code, c("new", "var", "sexage"))

# check to see if `iso2` and `iso3` are redundant
who.2 <- who %>% select(country, iso2,iso3) %>% distinct()
length(unique(who.2$country))
length(unique(who.2$iso2))
length(unique(who.2$iso3))
```

## 4. For each country, year, and sex compute the total number of cases of TB. Make an informative visualisation of the data.
```{r}
who <- who %>% select(-iso2,-iso3,-new) %>% separate(sexage,c('sex','age'),sep=1)

who %>% group_by(country,year,sex) %>% summarize(cases=sum(value)) %>% ggplot(aes(x=year,y=cases,group=country,colour=sex)) + geom_point()
```

